# Generated by Django 4.2.1 on 2023-05-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_about_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event/default_event.png', upload_to='event/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('passed', 'Прошедший')], default='new'),
        ),
    ]
