# Generated by Django 4.2.1 on 2023-05-22 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('events', '0004_alter_event_image_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.address'),
        ),
    ]
