# Generated by Django 4.2.1 on 2023-05-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('passed', 'Passed')], default='new'),
        ),
    ]
