# Generated by Django 4.2.1 on 2023-06-04 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0011_event_creator_delete_userevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creator',
        ),
        migrations.AddField(
            model_name='event',
            name='lectors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
