version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  api:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py migrate

  db:
    image: postgres:latest
    ports:
      - "5555:5432"
    env_file:
      - ./backend/.env
    healthcheck:
      test: pg_isready -U admin -d znanie
      interval: 3s
      retries: 10
      timeout: 3s
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
volumes:
  pgdata:
