# Generated by Django 4.2.1 on 2023-05-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_address_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='population',
        ),
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('city', 'г.'), ('village', 'д.')], default='city'),
        ),
    ]
