# Generated by Django 4.2.1 on 2023-05-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='graduated_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user/default_user.png', upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='work',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
