# Generated by Django 4.2.1 on 2023-05-22 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('users', '0004_alter_education_graduated_year_alter_education_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
