# Generated by Django 4.2.1 on 2023-05-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_address_delete_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favourites',
        ),
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
    ]
