# Generated by Django 4.2.1 on 2023-05-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_status'),
        ('users', '0008_remove_user_likes_delete_userlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='events.event'),
        ),
    ]
