# Generated by Django 4.2.1 on 2023-05-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_status'),
        ('users', '0009_user_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(related_name='events', to='events.event'),
        ),
        migrations.AddField(
            model_name='user',
            name='favourites',
            field=models.ManyToManyField(related_name='favourites', to='events.event'),
        ),
    ]
