# Generated by Django 4.2.1 on 2023-05-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_status'),
        ('users', '0010_user_events_user_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
        migrations.AddField(
            model_name='user',
            name='created_events',
            field=models.ManyToManyField(related_name='created', to='events.event'),
        ),
        migrations.AddField(
            model_name='user',
            name='selected_events',
            field=models.ManyToManyField(related_name='selected', to='events.event'),
        ),
    ]
