# Generated by Django 4.2.1 on 2023-05-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_email_alter_user_patronymic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('lector', 'Author')], default='user', max_length=30),
        ),
    ]
