# Generated by Django 4.2.1 on 2023-05-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_image'),
        ('users', '0015_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='as_lector_events',
            field=models.ManyToManyField(related_name='as_lector', to='events.event'),
        ),
    ]
