# Generated by Django 4.2.1 on 2023-06-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_as_lector_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='as_lector_events',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_events',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favourites',
        ),
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='selected_events',
        ),
    ]
