# Generated by Django 4.2.1 on 2023-06-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_creator_delete_userevent'),
        ('users', '0017_remove_user_as_lector_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_events',
            field=models.ManyToManyField(related_name='created', to='events.event'),
        ),
        migrations.AddField(
            model_name='user',
            name='favourites',
            field=models.ManyToManyField(related_name='favourites', to='events.event'),
        ),
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='events.event'),
        ),
        migrations.AddField(
            model_name='user',
            name='selected_events',
            field=models.ManyToManyField(related_name='selected', to='events.event'),
        ),
    ]
